const rawArtworks = [
  {
    "id": "art-2026-07-31-03",
    "title": "test1",
    "year": 2026,
    "media": "Deltarune",
    "genre": "Sci-Fi",
    "medium": "Digital Painting",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/proceed.png",
    "tags": ["Cyberpunk", "Neon", "Anime"],
    "description": "An exploration of retro-futuristic cityscape aesthetics."
  },
  {
    "id": "art-2026-07-31-02",
    "title": "test2",
    "year": 2026,
    "media": "Deltarune",
    "genre": "Fantasy",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/bou%20d.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-07-31-01",
    "title": "test3",
    "year": 2026,
    "media": "Undertale",
    "genre": "Fantasy",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/papy%20sans.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-07-31-00",
    "title": "test4",
    "year": 2026,
    "media": "Deltarune",
    "genre": "Fantasy",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/deltarune2.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-04-19-00",
    "title": "testsetset",
    "year": 2026,
    "media": "The Amazing Digital Circus",
    "genre": "test",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/caine.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-04-19-01",
    "title": "test6",
    "year": 2026,
    "media": "Project Hail Mary",
    "genre": "test",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/grace.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-04-19-02",
    "title": "test7",
    "year": 2026,
    "media": "Project Hail Mary",
    "genre": "test",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/uhm.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-04-24-00",
    "title": "test8",
    "year": 2026,
    "media": "Deltarune",
    "genre": "test",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/gasssstererer.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-04-28-00",
    "title": "test9",
    "year": 2026,
    "media": "Undertale",
    "genre": "test",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/hand.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-06-04-00",
    "title": "test9",
    "year": 2026,
    "media": "The Amazing Digital Circus",
    "genre": "test",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/jaxxy-protected-intensity-DEFAULT-V1.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-06-08-00",
    "title": "test9",
    "year": 2026,
    "media": "Persona 6",
    "genre": "test",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/p6.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-06-09-00",
    "title": "test9",
    "year": 2026,
    "media": "Backrooms",
    "genre": "test",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/backrooms.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-06-10-00",
    "title": "test9",
    "year": 2026,
    "media": "Backrooms",
    "genre": "test",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/theloveosv.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-06-10-01",
    "title": "test9",
    "year": 2026,
    "media": "Deltarune",
    "genre": "test",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/DELTARUNETMR.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-06-10-02",
    "title": "test9",
    "year": 2026,
    "media": "Backrooms",
    "genre": "test",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/asvasv%20ver2.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-06-16-00",
    "title": "test9",
    "year": 2026,
    "media": "Backrooms",
    "genre": "test",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/cards1.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-06-16-01",
    "title": "test9",
    "year": 2026,
    "media": "Backrooms",
    "genre": "test",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/go.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-06-16-02",
    "title": "test9",
    "year": 2026,
    "media": "Backrooms",
    "genre": "test",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/stop.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-06-17-00",
    "title": "test9",
    "year": 2026,
    "media": "Undertale",
    "genre": "test",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/hands.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-06-18-00",
    "title": "test9",
    "year": 2026,
    "media": "Backrooms",
    "genre": "test",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/sign1.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-06-18-01",
    "title": "test9",
    "year": 2026,
    "media": "Backrooms",
    "genre": "test",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/sign2.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  {
    "id": "art-2026-06-19-00",
    "title": "test9",
    "year": 2026,
    "media": "Deltarune",
    "genre": "test",
    "medium": "Pixel Art",
    "tools": "Clip Studio Paint",
    "image": "https://file.garden/ZxeJbwpMpVUTaKTZ/art/noebil.png",
    "tags": ["Pixel", "Fantasy"],
    "description": "Candy canes sweet roll halvah marzipan chocolate cake lollipop."
  },
  
]

export default function() {
  return rawArtworks.sort((a, b) => b.id.localeCompare(a.id));
}